# Generated by Django 6.0.3 on 2026-07-29 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosco", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarjeta",
            name="codigo",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
