# Generated by Django 6.0.3 on 2026-03-12 02:27

import comedor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valediario',
            name='comprobante',
            field=models.ImageField(blank=True, default='default/noticket.png', null=True, upload_to=comedor.models.picture_upload_to, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='valediario',
            name='fecha',
            field=models.DateField(),
        ),
    ]
