# Generated by Django 6.0.3 on 2026-03-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0004_alter_valediario_comprobante_alter_valediario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valediario',
            name='comentarios',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valemensual',
            name='comentarios',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
