# Generated by Django 6.0.3 on 2026-03-15 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0005_alter_valediario_comentarios_and_more'),
        ('escuela', '0003_cliente_limite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(max_length=30)),
                ('asistio', models.BooleanField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.cliente')),
            ],
            options={
                'unique_together': {('fecha', 'cliente')},
            },
        ),
    ]
