# Generated by Django 6.0.3 on 2026-07-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedor", "0006_asistencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precio",
            name="alm_por_sem",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="precio",
            name="nro_de_cliente",
            field=models.IntegerField(),
        ),
    ]
