# Generated by Django 6.0.3 on 2026-07-31 00:37

import comedor.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedor", "0007_alter_precio_alm_por_sem_alter_precio_nro_de_cliente"),
        ("escuela", "0003_cliente_limite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionComedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "porcentaje_devolucion_inasistencia",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.60"),
                        help_text="Fracción devuelta por inasistencia avisada en plan de 5 días (0.60 = 60%).",
                        max_digits=4,
                    ),
                ),
                (
                    "divisor_valor_dia",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Divisor del precio mensual para obtener el valor de un día (por defecto 20).",
                    ),
                ),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración de comedor",
                "verbose_name_plural": "Configuración de comedor",
            },
        ),
        migrations.CreateModel(
            name="CuentaComedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Positivo = debe; negativo = a favor. Cache de la suma de movimientos.",
                        max_digits=12,
                    ),
                ),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuenta_comedor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta de comedor",
                "verbose_name_plural": "Cuentas de comedor",
            },
        ),
        migrations.CreateModel(
            name="MovimientoComedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CARGO_MENSUAL", "Cargo mensual"),
                            ("CARGO_VALE_DIARIO", "Cargo vale diario"),
                            ("PAGO", "Pago"),
                            ("AJUSTE", "Ajuste"),
                            ("CREDITO_INASISTENCIA", "Crédito por inasistencia"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Firmado: positivo suma deuda (cargos); negativo la baja (pagos/créditos).",
                        max_digits=12,
                    ),
                ),
                ("concepto", models.CharField(blank=True, default="", max_length=200)),
                (
                    "periodo",
                    models.CharField(
                        blank=True,
                        help_text="AAAA-MM (solo para cargos mensuales).",
                        max_length=7,
                        null=True,
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="comedor.cuentacomedor",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Inasistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(help_text="Día de la ausencia.")),
                ("avisado_en", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("DEVOLUCION", "Devolución de dinero (plan 5 días)"),
                            ("VALE_A_FAVOR", "Vale a favor (plan 1-4 días)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "monto_devuelto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inasistencias",
                        to="escuela.cliente",
                    ),
                ),
                (
                    "movimiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="comedor.movimientocomedor",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudPagoComedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "comprobante",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=comedor.models.comprobante_pago_comedor_upload_to,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("resuelto_en", models.DateTimeField(blank=True, null=True)),
                (
                    "movimiento",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitud_pago",
                        to="comedor.movimientocomedor",
                    ),
                ),
                (
                    "resuelto_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_comedor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de pago de comedor",
                "verbose_name_plural": "Solicitudes de pago de comedor",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="ValeAFavor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("usado", models.BooleanField(default=False)),
                (
                    "fecha_uso",
                    models.DateField(
                        blank=True,
                        help_text="Día futuro elegido para usar el almuerzo a favor.",
                        null=True,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vales_a_favor",
                        to="escuela.cliente",
                    ),
                ),
                (
                    "inasistencia",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vale_a_favor",
                        to="comedor.inasistencia",
                    ),
                ),
                (
                    "vale_diario",
                    models.OneToOneField(
                        blank=True,
                        help_text="ValeDiario gratis generado al usar este vale a favor.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origen_a_favor",
                        to="comedor.valediario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vale a favor",
                "verbose_name_plural": "Vales a favor",
                "ordering": ["-creado"],
            },
        ),
        migrations.AddConstraint(
            model_name="movimientocomedor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tipo", "CARGO_MENSUAL")),
                fields=("cuenta", "periodo"),
                name="unico_cargo_mensual_por_periodo",
            ),
        ),
        migrations.AddConstraint(
            model_name="inasistencia",
            constraint=models.UniqueConstraint(
                fields=("cliente", "fecha"), name="una_inasistencia_por_cliente_dia"
            ),
        ),
    ]
