# Generated by Django 6.0.3 on 2026-07-31 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comedor",
            "0008_cuenta_comedor",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="valemensual",
            name="vigente_desde",
            field=models.DateField(blank=True, null=True),
        ),
    ]
