# Generated by Django 6.0.3 on 2026-07-31 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedor", "0009_valemensual_vigente_desde"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientocomedor",
            name="vale_diario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos_comedor",
                to="comedor.valediario",
            ),
        ),
    ]
