# Generated by Django 6.0.3 on 2026-07-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedor", "0010_movimientocomedor_vale_diario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inasistencia",
            name="resultado",
            field=models.CharField(
                choices=[
                    ("DEVOLUCION", "Devolución de dinero (plan 5 días)"),
                    ("VALE_A_FAVOR", "Vale a favor (plan 1-4 días)"),
                    ("SIN_COMPENSACION", "Sin compensación (aviso tardío)"),
                ],
                max_length=20,
            ),
        ),
    ]
