"""
Django settings for kiosco_sole project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# La clave se lee de la variable de entorno DJANGO_SECRET_KEY. El valor por
# defecto (inseguro) es solo para desarrollo local. En producción DEBES definir
# DJANGO_SECRET_KEY con un valor largo y aleatorio (y rotar el que estaba en el repo).
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-(0#unw-n0(@ar(0va)x1&kmcal1%3ru)o6y0!)8z#5jlvg(aqm'
)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG se controla por variable de entorno; por defecto queda apagado.
# Para desarrollo local: export DJANGO_DEBUG=True
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

# ALLOWED_HOSTS = ['yourdomain.com', 'your-server-ip'] - Ajuste de Lanzamiento
ALLOWED_HOSTS = [
    'www.comedormila.com.ar', 
    '127.0.0.1', 
    'localhost']

CSRF_TRUSTED_ORIGINS = [
    'https://nicocalvino.pythonanywhere.com',
    'https://www.comedormila.com.ar',
    'https://comedormila.com.ar' # Por si entran sin el www
]
# Application definition

INSTALLED_APPS = [
    'users',
    'admin_honeypot',
    'axes',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'main',
    'kiosco',
    'productos',
    'transacciones',
    'comedor',
    'escuela',
    'menu'
]

AUTHENTICATION_BACKENDS = [
    # Axes debe ir primero para poder bloquear antes de que Django autentique
    'axes.backends.AxesStandaloneBackend',
    
    # El backend por defecto de Django
    'django.contrib.auth.backends.ModelBackend',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'main.middleware.StaffOTPRequiredMiddleware'
]

# El sitio no debe poder embeberse en iframes de terceros (anti-clickjacking).
X_FRAME_OPTIONS = 'DENY'

ROOT_URLCONF = 'kiosco_sole.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kiosco_sole.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [BASE_DIR / "static"]

# Defaul primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


AUTH_USER_MODEL = "users.Perfil"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Carpeta local desde donde la importación por Excel de vales diarios lee los
# comprobantes (imágenes). Configurable por entorno; por defecto media/import_comprobantes.
COMPROBANTES_IMPORT_DIR = os.environ.get(
    'COMPROBANTES_IMPORT_DIR',
    str(BASE_DIR / 'media' / 'import_comprobantes')
)

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Configuraciones de Axes
AXES_FAILURE_LIMIT = 5            # Bloquea al 5to intento fallido
AXES_COOLOFF_TIME = 1             # El bloqueo dura 1 hora (en horas)
AXES_USERNAME_FORM_FIELD = 'username'
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True  # Bloquea la dupla Usuario+IP
AXES_RESET_ON_SUCCESS = True      # Si se loguea bien, se resetea el contador

AXES_LOCKOUT_URL = '/acceso-denegado/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Cabeceras de seguridad
# ---------------------------------------------------------------------------
# Evita que el navegador "adivine" el tipo de contenido (protección XSS/MIME).
SECURE_CONTENT_TYPE_NOSNIFF = True
# (X_FRAME_OPTIONS = 'DENY' se define más arriba, junto al middleware.)

# Los siguientes ajustes solo se activan en producción (DEBUG=False) para no
# romper el desarrollo local sobre http://127.0.0.1.
if not DEBUG:
    # Redirige todo el tráfico HTTP a HTTPS.
    SECURE_SSL_REDIRECT = True
    # Las cookies de sesión y CSRF solo viajan por HTTPS.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HTTP Strict Transport Security: fuerza HTTPS por 1 año.
    # (Activar con cuidado; una vez enviado, el navegador lo recuerda.)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Necesario si se corre detrás de un proxy/reverse-proxy con HTTPS
    # (como PythonAnywhere). Django reconoce así que la conexión es segura.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')