# Generated by Django 6.0.3 on 2026-03-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='limite',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
    ]
