# Generated by Django 6.0.3 on 2026-10-04 17:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0005_cargar_turnos_iniciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONSUMO', 'Consumo del colegio'), ('CANON', 'Canon de concesión')], default='CONSUMO', max_length=10)),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_cuenta', to='escuela.colegio')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de cuenta del colegio',
                'verbose_name_plural': 'Movimientos de cuenta del colegio',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MesColegioPagado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meses_pagados', to='escuela.colegio')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mes pagado al colegio',
                'verbose_name_plural': 'Meses pagados al colegio',
                'constraints': [models.UniqueConstraint(fields=('colegio', 'year', 'month'), name='mes_colegio_pagado_unico')],
            },
        ),
    ]
