# Generated by Django 6.0.3 on 2026-03-12 02:27

import transacciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcarga',
            name='comprobante',
            field=models.ImageField(blank=True, default='default/noticket.png', null=True, upload_to=transacciones.models.picture_upload_to, verbose_name='Comprobante'),
        ),
    ]
