# Generated by Django 6.0.3 on 2026-04-14 17:55

import transacciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_alter_solicitudcarga_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcarga',
            name='comprobante',
            field=models.FileField(blank=True, default='default/noticket.png', null=True, upload_to=transacciones.models.picture_upload_to, verbose_name='Comprobante'),
        ),
    ]
