# Generated by Django 6.0.3 on 2026-07-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transacciones", "0004_alter_solicitudcarga_comprobante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaccion",
            name="concepto",
            field=models.CharField(
                choices=[("CARGA SALDO", "Carga de saldo"), ("COMPRA", "Compra")],
                max_length=30,
            ),
        ),
    ]
