# Generated by Django 6.0.3 on 2026-03-17 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('PLATO PRINCIPAL', 'Plato Principal'), ('PLATO ALTERNATIVO', 'Plato Alternativo'), ('POSTRE', 'Postre')], max_length=80)),
                ('ingrediente_principal', models.CharField(choices=[('POLLO', 'Pollo'), ('CERDO', 'Cerdo'), ('CARNE PICADA', 'Carne Picada')], max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miercoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=9)),
                ('plato_alternativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plato_alternativo', to='menu.plato')),
                ('plato_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plato_principal', to='menu.plato')),
                ('postre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postre', to='menu.plato')),
            ],
        ),
    ]
