# Generated by Django 6.0.3 on 2026-03-18 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='plato_alternativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plato_alternativo', to='menu.plato'),
        ),
    ]
