# Generated by Django 6.0.3 on 2026-03-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_feriados_plato_dia_fijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='fecha',
            field=models.DateField(unique=True),
        ),
    ]
