# Generated by Django 6.0.3 on 2026-03-18 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menu_fecha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feriados',
            new_name='Feriado',
        ),
        migrations.AlterField(
            model_name='menu',
            name='dia',
            field=models.CharField(blank=True, choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miercoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=9),
        ),
        migrations.AlterField(
            model_name='menu',
            name='plato_alternativo',
            field=models.ForeignKey(blank=True, limit_choices_to={'categoria': 'PLATO ALTERNATIVO'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus_alternativos', to='menu.plato'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='plato_principal',
            field=models.ForeignKey(limit_choices_to={'categoria': 'PLATO PRINCIPAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='menus_principales', to='menu.plato'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='postre',
            field=models.ForeignKey(limit_choices_to={'categoria': 'POSTRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='menus_postres', to='menu.plato'),
        ),
    ]
