# Generated by Django 6.0.3 on 2026-08-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_rename_feriados_feriado_alter_menu_dia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuJardin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("LUNES", "Lunes"),
                            ("MARTES", "Martes"),
                            ("MIERCOLES", "Miercoles"),
                            ("JUEVES", "Jueves"),
                            ("VIERNES", "Viernes"),
                        ],
                        max_length=9,
                        unique=True,
                    ),
                ),
                (
                    "plato_principal",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("postre", models.CharField(blank=True, default="", max_length=200)),
                ("orden", models.PositiveSmallIntegerField(default=0, editable=False)),
            ],
            options={
                "verbose_name": "Menú de jardín",
                "verbose_name_plural": "Menú de jardín",
                "ordering": ["orden"],
            },
        ),
    ]
